# Generated by Django 5.1.1 on 2024-11-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='никнейм', max_length=30)),
                ('firstname', models.CharField(help_text='Имя', max_length=20)),
                ('lastname', models.CharField(help_text='Фамилия', max_length=30)),
                ('email', models.CharField(help_text='Email', max_length=70)),
                ('password', models.CharField(help_text='Пароль', max_length=30)),
            ],
        ),
    ]
